### ISSUE TITLE
Have to Restart Plugin

### ISSUE THREAD

**Issue by sammuelb** [h4writer/enablegoogleinbox#1]
Enable Google Inbox 0.1.1 makes my life a lot easier by not having to do it manually, but I have to disable & re-enable the plug in every time I start Firefox.  It would be nice if I didn't have to do this.  I'm using Firefox 35.0.  It might be a conflict between plugins, but I'm not sure.  Let me know if you  want a list of the add ons I have for Firefox.

**Comment by h4writer** [comment]
That is strange.
1) There are two points of failure here. Can you help me distinguish what goes wrong?

Do you see the screen "Inbox only works on Chrome" or are you already a bit further and having your inbox getting loaded and visible, but a "loading" in the left corner?

2) Yeah listing your plugins might give me a clue.

**Comment by sammuelb** [comment]
I get the "Inbox only works on Chrome" screen every time I restart.

Here are screen grabs of my Extensions & my Plugins.

![extensions](https://cloud.githubusercontent.com/assets/10660288/5883825/bd7ec9de-a30a-11e4-959b-7d7547b02359.JPG)
![plugins](https://cloud.githubusercontent.com/assets/10660288/5883824/bd7dbe68-a30a-11e4-81bc-5de0a8840b48.JPG)

**Comment by h4writer** [comment]
Thanks for the info. So the first part fails, which tries to adjust the "user agent" for inbox.google.com. I don't really see other plugins that you have installed that do that.
But can you disable "premiumize me" and see if the issue still happens?

**Comment by sammuelb** [comment]
Disabling "Premiumize.me" didn't work, but I did just discover that I do NOT have to actually disable & re-enable your "Enable Google Inbox" extension when I start up Firefox, I just have to hit the Refresh button & Inbox comes right up.  I believe my issue has to do with the fact that I have Inbox as a "pinned" tab and that I have Firefox set to "show my windows & tabs from last time".  So I think that Inbox tries to connect before the extension is activated.  If I close the "pinned" inbox tab, then restart Firefox, then open a new tab & go to Inbox, everything works fine.

**Comment by h4writer** [comment]
That sounds very plausible. Though I have no idea how I can fix that or work around that issue (yet?).

**Comment by rneacsu** [comment]
I have the same issue here. When I start Firefox I always have to reload the Inbox page for the plug-in to do its work and the message "Inbox only works on Chrome" to disappear. I believe the fact that I also have the tabbed pinned is causing the problem. I also noticed that the Hangout sidebar is loading forever until I give the page another reload. Strange.

**Comment by h4writer** [comment]
see #3
