### ISSUE TITLE
Stopped working (Google change?)

### ISSUE THREAD

**Issue by JonathanHarford** [h4writer/enablegoogleinbox#3]
I installed this add-on yesterday (Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:35.0) Gecko/20100101 Firefox/35.0), and it worked great. Then I installed it on another machine last night (same setup), and it didn't work. I thought it must have been due to quirk with the second machine, but now it's not working on the first machine either.

**Comment by h4writer** [comment]
I just tried on Ubuntu using Firefox 35.0.1 on a new profile and I'm seeing no problems here.
Could you try a hard refresh: ctrl+f5 and see if starts working again?

**Comment by JonathanHarford** [comment]
Just went to it and it works! Maybe it was something on the Google end?
Sorry to trouble you.

**Comment by JonathanHarford** [comment]
Ah. I see that when I close the browser and reopen it, the tab goes to the
"Inbox doesn't work with your browser" page. But a refresh actually gets me
to Inbox, whereas the other day it did not.

**Comment by h4writer** [comment]
https://github.com/h4writer/enablegoogleinbox/commit/f8a755f97951e58834cf06476c0c3afcdeb8bc6d
So for some odd reason sometimes the hooks don't get installed before the website is loaded. I added an extra check that will reload the page if that happens. So this should be solved in the newest version 0.1.2 which should be rolling out after the review. tomorrowish?

The xpi in the repo already contains the fix:
https://github.com/h4writer/enablegoogleinbox/blob/master/enable-google-inbox.xpi
